// src/pages/BookingHistoryPage.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { bookingAPI } from '../services/api';
import { jsPDF } from 'jspdf';
import {
  FaBoxOpen, FaTruck, FaShip, FaPlane, FaTrain, FaAnchor,
  FaMapMarkerAlt, FaCalendarAlt, FaWeight, FaRupeeSign,
  FaDownload, FaSearchLocation, FaTimes, FaPlus, FaChevronRight,
  FaCheckCircle, FaClock, FaTimesCircle, FaBoxes,
} from 'react-icons/fa';

interface Booking {
  id: string;
  booking_number: string;
  service_type: string;
  status: string;
  booking_date: string;
  estimated_price: number;
  origin: string;
  destination: string;
  cargo_type: string;
  weight: number;
  container_type?: string;
  number_of_containers?: number;
}

const getServiceIcon = (type: string) => {
  switch (type?.toLowerCase()) {
    case 'truck':   return <FaTruck className="text-orange-500" />;
    case 'sea':     return <FaShip className="text-blue-500" />;
    case 'air':     return <FaPlane className="text-sky-500" />;
    case 'rail':
    case 'train':   return <FaTrain className="text-green-500" />;
    case 'port':    return <FaAnchor className="text-indigo-500" />;
    case 'parcel':  return <FaBoxes className="text-yellow-500" />;
    default:        return <FaBoxOpen className="text-gray-400" />;
  }
};

const getStatusConfig = (status: string) => {
  switch (status?.toLowerCase()) {
    case 'confirmed': return { label: 'Confirmed', pill: 'bg-green-50 text-green-700 border border-green-200', dot: 'bg-green-500', border: '#22c55e' };
    case 'pending':   return { label: 'Pending',   pill: 'bg-yellow-50 text-yellow-700 border border-yellow-200', dot: 'bg-yellow-500', border: '#eab308' };
    case 'delivered': return { label: 'Delivered', pill: 'bg-blue-50 text-blue-700 border border-blue-200', dot: 'bg-blue-500', border: '#3b82f6' };
    case 'cancelled': return { label: 'Cancelled', pill: 'bg-red-50 text-red-700 border border-red-200', dot: 'bg-red-500', border: '#ef4444' };
    default:          return { label: status,      pill: 'bg-gray-50 text-gray-600 border border-gray-200', dot: 'bg-gray-400', border: 'transparent' };
  }
};

const BookingCard: React.FC<{ booking: Booking }> = ({ booking }) => {
  const navigate = useNavigate();
  const statusConfig = getStatusConfig(booking.status);
  const [expanded, setExpanded] = useState(false);
  const [details, setDetails] = useState<any>(null);
  const [loadingDetails, setLoadingDetails] = useState(false);

  const toggleExpand = async () => {
    const next = !expanded;
    setExpanded(next);
    if (next && !details) {
      setLoadingDetails(true);
      try {
        const res = await bookingAPI.getById(booking.id);
        setDetails(res.data?.data || res.data || null);
      } catch { /* fall back to the list data we already have */ }
      finally { setLoadingDetails(false); }
    }
  };

  const handleDownload = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setTextColor(37, 99, 235);
    doc.text('SHIPPITIN', 20, 20);
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text('Booking Summary', 20, 28);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 32, 190, 32);
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(12);
    const lines = [
      `Booking ID    : ${booking.booking_number}`,
      `Service       : ${booking.service_type}`,
      `From          : ${booking.origin}`,
      `To            : ${booking.destination}`,
      `Date          : ${new Date(booking.booking_date).toLocaleDateString('en-IN')}`,
      `Weight        : ${booking.weight} kg`,
      `Cargo Type    : ${booking.cargo_type}`,
      `Status        : ${booking.status}`,
      `Amount        : Rs ${(booking.estimated_price || 0).toLocaleString('en-IN')}`,
    ];
    lines.forEach((line, i) => doc.text(line, 20, 44 + i * 12));
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Shippitin Logistics · shippitin.co', 20, 180);
    doc.save(`${booking.booking_number}_summary.pdf`);
  };

  return (
    <div
      className="bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-all duration-200 overflow-hidden"
      style={{ borderLeft: `4px solid ${statusConfig.border}` }}
    >
      <div className="p-6">
        {/* Header row */}
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gray-50 rounded-xl flex items-center justify-center text-lg">
              {getServiceIcon(booking.service_type)}
            </div>
            <div>
              <p className="font-bold text-blue-600 text-base">{booking.booking_number}</p>
              <p className="text-xs text-gray-400">{booking.service_type}</p>
            </div>
          </div>
          <span className={`text-xs font-semibold px-3 py-1 rounded-full ${statusConfig.pill}`}>
            {statusConfig.label}
          </span>
        </div>

        {/* Details grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
          <div>
            <p className="text-xs text-gray-400 mb-0.5 flex items-center gap-1"><FaMapMarkerAlt className="text-xs" />FROM</p>
            <p className="text-sm font-semibold text-gray-700 truncate">{booking.origin}</p>
          </div>
          <div>
            <p className="text-xs text-gray-400 mb-0.5 flex items-center gap-1"><FaMapMarkerAlt className="text-xs" />TO</p>
            <p className="text-sm font-semibold text-gray-700 truncate">{booking.destination}</p>
          </div>
          <div>
            <p className="text-xs text-gray-400 mb-0.5 flex items-center gap-1"><FaCalendarAlt className="text-xs" />DATE</p>
            <p className="text-sm font-semibold text-gray-700">{new Date(booking.booking_date).toLocaleDateString('en-IN')}</p>
          </div>
          <div>
            <p className="text-xs text-gray-400 mb-0.5 flex items-center gap-1"><FaWeight className="text-xs" />CARGO</p>
            <p className="text-sm font-semibold text-gray-700 truncate">{booking.cargo_type || 'General'}</p>
          </div>
        </div>

        {/* Footer: amount + actions */}
        <div className="flex items-center justify-between pt-4 border-t border-gray-50">
          <p className="text-xl font-black text-gray-900 flex items-center gap-1">
            <FaRupeeSign className="text-base text-blue-500" />
            {(booking.estimated_price || 0).toLocaleString('en-IN')}
          </p>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-600 text-xs font-semibold transition"
            >
              <FaDownload className="text-xs" /> PDF
            </button>
            <button
              onClick={() => navigate(`/track?id=${booking.booking_number}`)}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-blue-50 hover:bg-blue-100 text-blue-600 text-xs font-semibold transition"
            >
              <FaSearchLocation className="text-xs" /> Track
            </button>
            <button
              onClick={() => bookingAPI.cancel(booking.id).then(() => window.location.reload())}
              disabled={booking.status === 'cancelled' || booking.status === 'delivered'}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-red-50 hover:bg-red-100 text-red-500 text-xs font-semibold transition disabled:opacity-30 disabled:cursor-not-allowed"
            >
              <FaTimes className="text-xs" /> Cancel
            </button>
          </div>
        </div>

        {/* View details — full booking breakdown */}
        <button
          onClick={toggleExpand}
          className="mt-4 w-full flex items-center justify-center gap-1.5 text-xs font-semibold text-blue-600 hover:text-blue-700"
        >
          {expanded ? 'Hide details' : 'View details'}
          <FaChevronRight className={`text-[10px] transition-transform ${expanded ? 'rotate-90' : ''}`} />
        </button>

        {expanded && (
          <div className="mt-3 pt-4 border-t border-gray-100">
            {loadingDetails ? (
              <p className="text-xs text-gray-400 text-center py-2">Loading details…</p>
            ) : (
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-4 gap-y-3">
                {(() => {
                  const d: any = { ...booking, ...(details || {}) };
                  const rows: [string, any][] = [
                    ['Booking Type',     d.service_type],
                    ['Container Type',   d.container_type],
                    ['No. of Containers', d.number_of_containers],
                    ['Weight',           d.weight ? `${d.weight} KG` : null],
                    ['Cargo Type',       d.cargo_type],
                    ['Origin',           d.origin],
                    ['Destination',      d.destination],
                    ['Booking Date',     d.booking_date ? new Date(d.booking_date).toLocaleDateString('en-IN') : null],
                    ['Amount',           d.estimated_price != null ? `₹${Number(d.estimated_price).toLocaleString('en-IN')}` : null],
                    ['Status',           statusConfig.label],
                  ];
                  return rows
                    .filter(([, v]) => v !== null && v !== undefined && v !== '')
                    .map(([label, value]) => (
                      <div key={label}>
                        <p className="text-[11px] text-gray-400 mb-0.5">{label}</p>
                        <p className="text-sm font-semibold text-gray-700 break-words">{value}</p>
                      </div>
                    ));
                })()}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

const BookingHistoryPage: React.FC = () => {
  const navigate = useNavigate();
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('All');

  useEffect(() => {
    const load = async () => {
      try {
        const response = await bookingAPI.getAll();
        setBookings(response.data.data || []);
      } catch (error) {
        console.error('Error fetching bookings:', error);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  const filters = ['All', 'pending', 'confirmed', 'delivered', 'cancelled'];
  const filtered = filter === 'All'
    ? bookings
    : bookings.filter(b => b.status.toLowerCase() === filter.toLowerCase());

  const counts = {
    All: bookings.length,
    pending:   bookings.filter(b => b.status.toLowerCase() === 'pending').length,
    confirmed: bookings.filter(b => b.status.toLowerCase() === 'confirmed').length,
    delivered: bookings.filter(b => b.status.toLowerCase() === 'delivered').length,
    cancelled: bookings.filter(b => b.status.toLowerCase() === 'cancelled').length,
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Sticky header */}
      <div className="sticky top-16 z-30 bg-white border-b border-gray-100 shadow-sm">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <h1 className="text-xl font-bold text-gray-800 flex items-center gap-2">
            <FaBoxOpen className="text-blue-500" /> My Bookings
          </h1>
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-xl text-sm font-bold transition"
          >
            <FaPlus className="text-xs" /> New Booking
          </button>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Stats row */}
        {!loading && bookings.length > 0 && (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
            {[
              { label: 'Confirmed', count: counts.confirmed, color: 'text-green-600', bg: 'bg-green-50' },
              { label: 'Pending',   count: counts.pending,   color: 'text-yellow-600', bg: 'bg-yellow-50' },
              { label: 'Delivered', count: counts.delivered, color: 'text-blue-600',   bg: 'bg-blue-50' },
              { label: 'Cancelled', count: counts.cancelled, color: 'text-red-500',    bg: 'bg-red-50' },
            ].map(s => (
              <div key={s.label} className={`${s.bg} rounded-xl p-4 text-center`}>
                <p className={`text-2xl font-black ${s.color}`}>{s.count}</p>
                <p className="text-xs text-gray-500 font-medium">{s.label}</p>
              </div>
            ))}
          </div>
        )}

        {/* Filter tabs */}
        <div className="flex gap-2 mb-6 flex-wrap">
          {filters.map(status => (
            <button
              key={status}
              onClick={() => setFilter(status)}
              className={`px-4 py-2 rounded-full text-sm font-semibold transition flex items-center gap-1.5 ${
                filter === status
                  ? 'bg-blue-600 text-white shadow-sm'
                  : 'bg-white text-gray-500 border border-gray-200 hover:border-blue-300 hover:text-blue-600'
              }`}
            >
              {status.charAt(0).toUpperCase() + status.slice(1)}
              <span className={`text-xs px-1.5 py-0.5 rounded-full font-bold ${
                filter === status ? 'bg-white/20 text-white' : 'bg-gray-100 text-gray-500'
              }`}>
                {counts[status as keyof typeof counts]}
              </span>
            </button>
          ))}
        </div>

        {/* Content */}
        {loading ? (
          <div className="space-y-4">
            {[1, 2, 3].map(i => (
              <div key={i} className="bg-white rounded-2xl border border-gray-100 p-6 animate-pulse">
                <div className="h-5 bg-gray-100 rounded w-1/3 mb-3" />
                <div className="h-4 bg-gray-100 rounded w-1/2" />
              </div>
            ))}
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-2xl border border-gray-100">
            <FaBoxOpen className="text-gray-200 text-6xl mx-auto mb-4" />
            <p className="text-gray-400 text-lg font-medium mb-2">No bookings found</p>
            <p className="text-gray-300 text-sm mb-6">
              {filter === 'All' ? 'Create your first booking to get started' : `No ${filter} bookings`}
            </p>
            {filter === 'All' && (
              <button
                onClick={() => navigate('/')}
                className="bg-blue-600 text-white px-6 py-2.5 rounded-xl font-bold hover:bg-blue-700 transition text-sm"
              >
                Create First Booking
              </button>
            )}
          </div>
        ) : (
          <div className="space-y-4">
            {filtered.map(booking => (
              <BookingCard key={booking.id} booking={booking} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default BookingHistoryPage;
